<a href="https://colab.research.google.com/github/MinChul-Son/Machine_Learning_study/blob/main/day1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import tensorflow as tf


In [ ]:
#파일들로부터 데이터 읽어오기
path= 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/lemonade.csv'
lemonade = pd.read_csv(path)

path= 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/boston.csv'
boston = pd.read_csv(path)

path= 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
iris = pd.read_csv(path)

In [ ]:
# 데이터 모양으로 확인 ==> (row, column)형태로 return
print(lemonade.shape)
print(boston.shape)
print(iris.shape)

(6, 2)
(506, 14)
(150, 5)


In [ ]:
# 칼럼이름 출력
print(lemonade.columns)
print(boston.columns)
print(iris.columns)

Index(['온도', '판매량'], dtype='object')
Index(['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'b', 'lstat', 'medv'],
      dtype='object')
Index(['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭', '품종'], dtype='object')


In [ ]:
#독립변수 종속변수 분류
independent = lemonade[['온도']]
dependent = lemonade[['판매량']]
print(independent.shape, dependent.shape)

independent = boston[['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'b', 'lstat']]
dependent = boston[['medv']]
print(independent.shape, dependent.shape)

independent = iris[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
dependent = iris[['품종']]
print(independent.shape, dependent.shape)


(6, 1) (6, 1)
(506, 13) (506, 1)
(150, 4) (150, 1)


In [ ]:
print(lemonade.head())

   온도  판매량
0  20   40
1  21   42
2  22   44
3  23   46
4  24   48


In [ ]:
print(boston.head())

      crim    zn  indus  chas    nox  ...  tax  ptratio       b  lstat  medv
0  0.00632  18.0   2.31     0  0.538  ...  296     15.3  396.90   4.98  24.0
1  0.02731   0.0   7.07     0  0.469  ...  242     17.8  396.90   9.14  21.6
2  0.02729   0.0   7.07     0  0.469  ...  242     17.8  392.83   4.03  34.7
3  0.03237   0.0   2.18     0  0.458  ...  222     18.7  394.63   2.94  33.4
4  0.06905   0.0   2.18     0  0.458  ...  222     18.7  396.90   5.33  36.2

[5 rows x 14 columns]


In [ ]:
print(iris.head())

   꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭      품종
0   5.1  3.5    1.4   0.2  setosa
1   4.9  3.0    1.4   0.2  setosa
2   4.7  3.2    1.3   0.2  setosa
3   4.6  3.1    1.5   0.2  setosa
4   5.0  3.6    1.4   0.2  setosa


In [ ]:
#--------------------------1.Lemonade predic Model-------------------
independent = lemonade[['온도']]
dependent = lemonade[['판매량']]

#1. 모델을 만든다.(make model)
X = tf.keras.layers.Input(shape=[1]) #독립변수의 칼럼 갯수 1개
Y = tf.keras.layers.Dense(1)(X)
model = tf.keras.models.Model(X, Y)
model.compile(loss='mse')


In [ ]:
#2. 모델을 학습시긴다.(Learning Model)
model.fit(independent, dependent, epochs=10)  #verbos=0을 입력하면 학습하는 동안 콘솔 출력 x, e-04= 10의 -4승 ==>1.8295e-04 == 0.0001

Epoch 1/10
1/1 [==============================] - 0s 4ms/step - loss: 1.8298e-04
Epoch 2/10
1/1 [==============================] - 0s 7ms/step - loss: 1.8295e-04
Epoch 3/10
1/1 [==============================] - 0s 5ms/step - loss: 1.8294e-04
Epoch 4/10
1/1 [==============================] - 0s 4ms/step - loss: 1.8290e-04
Epoch 5/10
1/1 [==============================] - 0s 5ms/step - loss: 1.8280e-04
Epoch 6/10
1/1 [==============================] - 0s 4ms/step - loss: 1.8272e-04
Epoch 7/10
1/1 [==============================] - 0s 4ms/step - loss: 1.8263e-04
Epoch 8/10
1/1 [==============================] - 0s 3ms/step - loss: 1.8253e-04
Epoch 9/10
1/1 [==============================] - 0s 3ms/step - loss: 1.8254e-04
Epoch 10/10
1/1 [==============================] - 0s 3ms/step - loss: 1.8253e-04


In [ ]:
model.predict(independent)

array([[40.02063 ],
       [42.01727 ],
       [44.013905],
       [46.010544],
       [48.00718 ],
       [50.00382 ]], dtype=float32)

In [ ]:
model.predict([[15]])

array([[30.037447]], dtype=float32)

In [ ]:
#----------------------2.Bostion House Price Predict-------------------------------
#1.데이터를 준비한다. (Prepare Data)
independent = boston[['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'b', 'lstat']]
dependent = boston[['medv']]

#2. 모델의 구조를 만든다. (Make Model)
X = tf.keras.layers.Input(shape=[13])
Y = tf.keras.layers.Dense(1)(X)
model = tf.keras.models.Model(X,Y)
model.compile(loss='mse') 




In [ ]:
#3. 모델을 학습시킵니다. (Fit Model)
model.fit(independent, dependent, epochs=10)


Epoch 1/10
16/16 [==============================] - 0s 1ms/step - loss: 26.4740
Epoch 2/10
16/16 [==============================] - 0s 1ms/step - loss: 26.2941
Epoch 3/10
16/16 [==============================] - 0s 1ms/step - loss: 26.1019
Epoch 4/10
16/16 [==============================] - 0s 1ms/step - loss: 26.0785
Epoch 5/10
16/16 [==============================] - 0s 1ms/step - loss: 26.0629
Epoch 6/10
16/16 [==============================] - 0s 1ms/step - loss: 26.1850
Epoch 7/10
16/16 [==============================] - 0s 1ms/step - loss: 25.9236
Epoch 8/10
16/16 [==============================] - 0s 1ms/step - loss: 26.0056
Epoch 9/10
16/16 [==============================] - 0s 1ms/step - loss: 26.3062
Epoch 10/10
16/16 [==============================] - 0s 1ms/step - loss: 26.0886


In [ ]:
model.predict(independent[0:5])

array([[28.814075],
       [24.104385],
       [29.81099 ],
       [29.165665],
       [28.518814]], dtype=float32)

In [ ]:
dependent[0:5]

medv
0  24.0
1  21.6
2  34.7
3  33.4
4  36.2

In [ ]:
#모델의 수식 확인(Check model's expression)
model.get_weights()

[array([[-0.08519736],
        [ 0.07219958],
        [-0.06301176],
        [ 3.4289684 ],
        [ 2.3830097 ],
        [ 3.9872563 ],
        [ 0.01309566],
        [-0.90100306],
        [ 0.15038723],
        [-0.01019472],
        [-0.006007  ],
        [ 0.01491302],
        [-0.5781094 ]], dtype=float32), array([2.9127398], dtype=float32)]

In [ ]:
#---------------------------3.iris cultivar predict------------ 분류 모델
path= 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
iris = pd.read_csv(path)
# 1. 원핫인코딩 (onehot-encoding)
encoding = pd.get_dummies(iris)
encoding.head()
print(encoding.columns)

Index(['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭', '품종_setosa', '품종_versicolor',
       '품종_virginica'],
      dtype='object')


In [ ]:
#1-1 독립변수와 종속 변수로 분리
independent = encoding[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
dependent = encoding[['품종_setosa', '품종_versicolor', '품종_virginica']]


In [ ]:
#2. 모델의 구조를 만듭니다. (Make Model)
X = tf.keras.layers.Input(shape=[4])
Y = tf.keras.layers.Dense(3,activation='softmax')(X)
model = tf.keras.models.Model(X,Y)
model.compile(loss='categorical_crossentropy', metrics='accuracy')

In [ ]:
#3. 모델을 학습시킵니다. (Fit Model)
model.fit(independent, dependent, epochs=100)

Epoch 1/100
5/5 [==============================] - 0s 2ms/step - loss: 0.5028 - accuracy: 0.9067
Epoch 2/100
5/5 [==============================] - 0s 2ms/step - loss: 0.5008 - accuracy: 0.9267
Epoch 3/100
5/5 [==============================] - 0s 2ms/step - loss: 0.5010 - accuracy: 0.8533
Epoch 4/100
5/5 [==============================] - 0s 2ms/step - loss: 0.4981 - accuracy: 0.9000
Epoch 5/100
5/5 [==============================] - 0s 2ms/step - loss: 0.4960 - accuracy: 0.9200
Epoch 6/100
5/5 [==============================] - 0s 2ms/step - loss: 0.4954 - accuracy: 0.9133
Epoch 7/100
5/5 [==============================] - 0s 2ms/step - loss: 0.4936 - accuracy: 0.9133
Epoch 8/100
5/5 [==============================] - 0s 2ms/step - loss: 0.4920 - accuracy: 0.9000
Epoch 9/100
5/5 [==============================] - 0s 2ms/step - loss: 0.4909 - accuracy: 0.9267
Epoch 10/100
5/5 [==============================] - 0s 2ms/step - loss: 0.4893 - accuracy: 0.9200
Epoch 11/100
5/5 [===========

In [ ]:
model.predict(independent[0:5])

array([[0.9402199 , 0.05490038, 0.00487976],
       [0.902735  , 0.08747882, 0.00978619],
       [0.918555  , 0.07398143, 0.0074635 ],
       [0.89559984, 0.09372938, 0.01067081],
       [0.943495  , 0.05203557, 0.00446952]], dtype=float32)

In [ ]:
print(dependent[0:5])

   품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0


In [ ]:
#학습한 가중치
model.get_weights()

[array([[ 0.51864094,  0.2026223 ,  0.11849657],
        [ 0.45575884, -0.43095678, -0.8573059 ],
        [-0.6084351 ,  0.09972545,  0.44893545],
        [-1.9522974 ,  0.51299554,  1.339832  ]], dtype=float32),
 array([ 0.17730048,  0.56742287, -0.58599925], dtype=float32)]

In [ ]:
#-------------------------4. Hidden Layer-----------------------------
#4-1 Boston
#1.데이터 준비(Prepare Data)
independent = boston[['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'b', 'lstat']]
dependent = boston[['medv']]

In [ ]:
#2. 모델을 만듭니다.(Make Model)
X = tf.keras.layers.Input(shape=[13])
H = tf.keras.layers.Dense(10, activation='swish')(X) #10개의 노드로 구성된 히든레이어 추가
Y = tf.keras.layers.Dense(1)(H)
model = tf.keras.models.Model(X,Y)
model.compile(loss='mse') 

In [ ]:
model.summary() #모델 확인

Model: "model_7"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_8 (InputLayer)         [(None, 13)]              0         
_________________________________________________________________
dense_9 (Dense)              (None, 10)                140       
_________________________________________________________________
dense_10 (Dense)             (None, 1)                 11        
Total params: 151
Trainable params: 151
Non-trainable params: 0
_________________________________________________________________


In [ ]:
#3. 모델을 학습시킨다. (Fit Model)
model.fit(independent, dependent, epochs=10)

Epoch 1/10
16/16 [==============================] - 0s 1ms/step - loss: 23.4372
Epoch 2/10
16/16 [==============================] - 0s 2ms/step - loss: 24.0474
Epoch 3/10
16/16 [==============================] - 0s 2ms/step - loss: 24.4225
Epoch 4/10
16/16 [==============================] - 0s 2ms/step - loss: 22.5655
Epoch 5/10
16/16 [==============================] - 0s 2ms/step - loss: 24.0420
Epoch 6/10
16/16 [==============================] - 0s 2ms/step - loss: 22.8970
Epoch 7/10
16/16 [==============================] - 0s 2ms/step - loss: 24.1218
Epoch 8/10
16/16 [==============================] - 0s 2ms/step - loss: 23.7018
Epoch 9/10
16/16 [==============================] - 0s 2ms/step - loss: 23.2914
Epoch 10/10
16/16 [==============================] - 0s 2ms/step - loss: 23.8663


In [ ]:
print(model.predict(independent[:5]))
print(dependent[:5])

[[25.772768]
 [20.82331 ]
 [26.911983]
 [26.682579]
 [26.078266]]
   medv
0  24.0
1  21.6
2  34.7
3  33.4
4  36.2


In [ ]:
#4-2 iris
path= 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
iris = pd.read_csv(path)
# 1. 원핫인코딩 (onehot-encoding)
encoding = pd.get_dummies(iris)
encoding.head()
print(encoding.columns)
independent = encoding[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
dependent = encoding[['품종_setosa', '품종_versicolor', '품종_virginica']]

Index(['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭', '품종_setosa', '품종_versicolor',
       '품종_virginica'],
      dtype='object')


In [ ]:
#2. 모델의 구조를 만듭니다. (Make Model)
X = tf.keras.layers.Input(shape=[4])
H = tf.keras.layers.Dense(8, activation='swish')(X)
H = tf.keras.layers.Dense(8, activation='swish')(X)
H = tf.keras.layers.Dense(8, activation='swish')(X)
Y = tf.keras.layers.Dense(3,activation='softmax')(H)
model = tf.keras.models.Model(X,Y)
model.compile(loss='categorical_crossentropy', metrics='accuracy')

In [ ]:
#3. 모델을 학습시킵니다. (Fit Model)
model.fit(independent, dependent, epochs=100)

In [ ]:
print(model.predict(independent[0:5]))
print(dependent[0:5])

[[9.9205363e-01 7.9458011e-03 5.5755982e-07]
 [9.7344548e-01 2.6548270e-02 6.2615741e-06]
 [9.8807585e-01 1.1922352e-02 1.7545347e-06]
 [9.8107970e-01 1.8915994e-02 4.2701463e-06]
 [9.9425393e-01 5.7457453e-03 3.3659381e-07]]
   품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0


In [ ]:
###########################
# 파일 읽어오기
파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris2.csv'
아이리스 = pd.read_csv(파일경로)
아이리스.head()
 
###########################
# 칼럼의 데이터 타입 체크
print(아이리스.dtypes)
 
# 원핫인코딩 되지 않는 현상 확인
인코딩 = pd.get_dummies(아이리스) #원핫인코딩은 데이터타입이 category이거나 object일때 가능 현재는 int형이므로 category형으로 바꿔준다.
인코딩.head()
 
###########################
# 품종 타입을 범주형으로 바꾸어 준다. 
아이리스['품종'] = 아이리스['품종'].astype('category')
print(아이리스.dtypes)
 
# 카테고리 타입의 변수만 원핫인코딩
인코딩 = pd.get_dummies(아이리스)
인코딩.head()
 
###########################
# NA값을 체크해 봅시다. 
아이리스.isna().sum()
아이리스.tail()
 
###########################
# NA값에 꽃잎폭 평균값을 넣어주는 방법
mean = 아이리스['꽃잎폭'].mean()
print(mean)
아이리스['꽃잎폭'] = 아이리스['꽃잎폭'].fillna(mean)
아이리스.tail()

꽃잎길이     float64
꽃잎폭      float64
꽃받침길이    float64
꽃받침폭     float64
품종         int64
dtype: object
꽃잎길이      float64
꽃잎폭       float64
꽃받침길이     float64
꽃받침폭      float64
품종       category
dtype: object
3.0543624161073835


꽃잎길이       꽃잎폭  꽃받침길이  꽃받침폭 품종
145   6.7  3.000000    5.2   2.3  2
146   6.3  2.500000    5.0   1.9  2
147   6.5  3.000000    5.2   2.0  2
148   6.2  3.400000    5.4   2.3  2
149   5.9  3.054362    5.1   1.8  2

In [ ]:
###########################
# 1.과거의 데이터를 준비합니다.
파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/boston.csv'
보스턴 = pd.read_csv(파일경로)
 
# 종속변수, 독립변수
독립 = 보스턴[['crim', 'zn', 'indus', 'chas', 'nox', 
            'rm', 'age', 'dis', 'rad', 'tax',
            'ptratio', 'b', 'lstat']]
종속 = 보스턴[['medv']]
print(독립.shape, 종속.shape)
 
###########################
# 2. 모델의 구조를 만듭니다
X = tf.keras.layers.Input(shape=[13])
H = tf.keras.layers.Dense(8, activation='swish')(X)
H = tf.keras.layers.Dense(8, activation='swish')(H)
H = tf.keras.layers.Dense(8, activation='swish')(H)
Y = tf.keras.layers.Dense(1)(H)
model = tf.keras.models.Model(X, Y)
model.compile(loss='mse')
 
# 2. 모델의 구조를 BatchNormalization layer를 사용하여 만든다.
X = tf.keras.layers.Input(shape=[13])
 
H = tf.keras.layers.Dense(8)(X)
H = tf.keras.layers.BatchNormalization()(H)
H = tf.keras.layers.Activation('swish')(H)
 
H = tf.keras.layers.Dense(8)(H)
H = tf.keras.layers.BatchNormalization()(H)
H = tf.keras.layers.Activation('swish')(H)
 
H = tf.keras.layers.Dense(8)(H)
H = tf.keras.layers.BatchNormalization()(H)
H = tf.keras.layers.Activation('swish')(H)
 
Y = tf.keras.layers.Dense(1)(H)
model = tf.keras.models.Model(X, Y)
model.compile(loss='mse')
 
###########################
# 3.데이터로 모델을 학습(FIT)합니다.
model.fit(독립, 종속, epochs=1000, verbose=0)

In [ ]:
###########################
# 1.과거의 데이터를 준비합니다.
파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
아이리스 = pd.read_csv(파일경로)
 
# 원핫인코딩
아이리스 = pd.get_dummies(아이리스)
 
# 종속변수, 독립변수
독립 = 아이리스[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
종속 = 아이리스[['품종_setosa', '품종_versicolor', '품종_virginica']]
print(독립.shape, 종속.shape)
 
###########################
# 2. 모델의 구조를 만듭니다
X = tf.keras.layers.Input(shape=[4])
H = tf.keras.layers.Dense(8, activation='swish')(X)
H = tf.keras.layers.Dense(8, activation='swish')(H)
H = tf.keras.layers.Dense(8, activation='swish')(H)
Y = tf.keras.layers.Dense(3, activation='softmax')(H)
model = tf.keras.models.Model(X, Y)
model.compile(loss='categorical_crossentropy',
              metrics='accuracy')
 
###########################
# 2. 모델의 구조를 BatchNormalization layer를 사용하여 만든다.
X = tf.keras.layers.Input(shape=[4])
 
H = tf.keras.layers.Dense(8)(X)
H = tf.keras.layers.BatchNormalization()(H)
H = tf.keras.layers.Activation('swish')(H)
 
H = tf.keras.layers.Dense(8)(H)
H = tf.keras.layers.BatchNormalization()(H)
H = tf.keras.layers.Activation('swish')(H)
 
H = tf.keras.layers.Dense(8)(H)
H = tf.keras.layers.BatchNormalization()(H)
H = tf.keras.layers.Activation('swish')(H)
 
Y = tf.keras.layers.Dense(3, activation='softmax')(H)
model = tf.keras.models.Model(X, Y)
model.compile(loss='categorical_crossentropy',
              metrics='accuracy')
               
###########################
# 3.데이터로 모델을 학습(FIT)합니다.
model.fit(독립, 종속, epochs=1000 verbose=0)